# Generated by Django 3.2.9 on 2022-05-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theonlyapp', '0002_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='cart',
            field=models.ManyToManyField(blank=True, to='theonlyapp.Cart'),
        ),
    ]
