# Generated by Django 3.2.9 on 2022-05-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theonlyapp', '0003_alter_mymodel_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('OLD', 'OLD')], default='NEW', max_length=3),
        ),
    ]
